# Generated by Django 5.2.1 on 2025-05-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncias', '0003_alter_denuncia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
