# Generated by Django 5.2.1 on 2025-05-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncias', '0004_denuncia_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
