# Generated by Django 5.2.3 on 2025-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncias', '0006_alter_denuncia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='categoria',
            field=models.CharField(choices=[('meio_ambiente', 'Meio Ambiente'), ('maus_tratos_animais', 'Maus-tratos a Animais'), ('perturbacao_sossego', 'Perturbação do Sossego'), ('obra_irregular', 'Obra Irregular'), ('acumulo_lixo', 'Acúmulo de Lixo'), ('poluicao_sonora', 'Poluição Sonora'), ('seguranca_publica', 'Segurança Pública'), ('violencia_domestica', 'Violência Doméstica'), ('tráfico_drogas', 'Tráfico de Drogas'), ('saude_publica', 'Saúde Pública'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='nome',
            field=models.CharField(blank=True, default='Anônimo', max_length=30),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='ponto_de_referencia',
            field=models.CharField(blank=True, help_text='Caso não tenha o endereço completo, descreva o local aqui.', max_length=50, null=True, verbose_name='Ponto de Referência'),
        ),
    ]
