# Generated by Django 5.2.3 on 2025-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncias', '0007_denuncia_bairro_denuncia_categoria_denuncia_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='categoria',
            field=models.CharField(choices=[('meio_ambiente', 'Meio Ambiente'), ('maus_tratos_animais', 'Maus-tratos a Animais'), ('perturbacao_sossego', 'Perturbação do Sossego'), ('obra_irregular', 'Obra Irregular'), ('acumulo_lixo', 'Acúmulo de Lixo'), ('poluicao_sonora', 'Poluição Sonora'), ('seguranca_publica', 'Segurança Pública'), ('violencia_domestica', 'Violência Doméstica'), ('tráfico_drogas', 'Tráfico de Drogas'), ('saude_publica', 'Saúde Pública'), ('outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
